Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "Leads",
 "business_name" => "Airport Service Provider Leads",
 "business_address" => "21807 Robledo rd\n" + "Palo Cedro, CA",
 "domain" => "example.com",
 "support_email" => "david@odeca.net",
 "default_from_email" => "My App <no-reply@example.com>",
 "background_job_processor" => "sidekiq",
 "email_provider" => "resend",
 "account_types" => "personal",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => [],
 "payment_processors" => [],
 "multitenancy" => [],
 "gems" => []})
